name: fdafiles

on:
  workflow_dispatch:

env:
  HF_DS_TICKERS: "jtviegas/ticker_analysis_tickers"
  HF_DS_PRICES: "jtviegas/ticker_analysis_prices"

jobs:
  execute_pipeline:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: 'install uv'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: 'setup python env'
      run: |
        uv venv .venv --python 3.11
    - name: 'install datasets library'
      run: uv pip install --python .venv/bin/python tgedr-datasets
    - name: 'get new prices'
      run: |
        .venv/bin/run --module tgedr_datasets.prices.etl \
          --classname PricesEtl \
          --callable run \
          --classparams "{\"configuration\": {\"tickers_dataset\": \"${{ env.HF_DS_TICKERS }}\", \"target_dataset\": \"${{ env.HF_DS_PRICES }}\"}}"
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
