name: fdafiles

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12.3"
  HF_DATASET_BRONZE: "jtviegas/faers_bronze"

jobs:
  execute_pipeline:
    runs-on: ubuntu-24.04
    # outputs:
    #   output: ${{ steps.py-step.outputs.run_next }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: 'install uv'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: 'setup python env'
      run: |
        uv venv .venv --python ${{ env.PYTHON_VERSION }}
    - name: 'install library'
      run: uv pip install --python .venv/bin/python tgedr-fdafaers
    - name: 'find periods to process'
      id: find_periods
      run: |
        uv run python --module tgedr_fdafaers.etl.periods_to_process \
          --classname Periods2Process \
          --callable run \
          --classparams "{\"configuration\": {\"bronze_dataset\": \"${{ env.HF_DATASET_BRONZE }}\"}}"
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
    - name: 'set output'
      run: |
        echo "Periods: ${{ steps.find_periods.outputs.result }}"
