name: fdafiles

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12.3"
  HF_DATASET_BRONZE_PREFIX: "jtviegas/faers_bronze_"
  HF_DATASET_BRONZE_DEMO: "jtviegas/faers_bronze_demo"
  MAX_PERIODS_TO_PROCESS: 3

jobs:
  execute_pipeline:
    runs-on: ubuntu-24.04
    # outputs:
    #   output: ${{ steps.py-step.outputs.run_next }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: 'install uv'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: 'setup python env'
      run: |
        uv venv .venv --python ${{ env.PYTHON_VERSION }}
    - name: 'install library'
      run: uv pip install --python .venv/bin/python tgedr-fdafaers
    - name: 'find periods to process'
      id: find_periods
      run: |
        uv run run --module tgedr_fdafaers.etl.periods_to_process \
          --classname Periods2Process \
          --callable run \
          --classparams "{\"configuration\": {\"bronze_dataset\": \"${{ env.HF_DATASET_BRONZE_DEMO }}\"}}"
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
    - name: 'fetch period files to process'
      if: steps.find_periods.outputs.result != ''
      id: fetch_period_files
      run: |
        uv run run --module tgedr_fdafaers.etl.fetch_period_files \
          --classname FetchPeriodFiles \
          --callable run \
          --classparams "{\"configuration\": {\"periods\": \"${{ steps.find_periods.outputs.result }}\", \"max_periods\": ${{ env.MAX_PERIODS_TO_PROCESS }}}}"
    - name: 'process period files'
      if: steps.fetch_period_files.outputs.result != ''
      id: process_period_files
      run: |
        uv run run --module tgedr_fdafaers.etl.process_period_files \
          --classname ProcessPeriodFiles \
          --callable run \
          --classparams "{\"configuration\": {\"files\": \"${{ steps.fetch_period_files.outputs.result }}\"}}"
    - name: 'ingest period files'
      if: steps.process_period_files.outputs.result != ''
      id: ingest_period_files
      run: |
        uv run run --module tgedr_fdafaers.etl.ingest_period_files \
          --classname IngestPeriodFiles \
          --callable run \
          --classparams "{\"configuration\": {\"files\": \"${{ steps.process_period_files.outputs.result }}\", \"dataset_prefix\": \"${{ env.HF_DATASET_BRONZE_PREFIX }}\"}}"
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
    - name: 'check output'
      run: |
        echo "Files: ${{ steps.ingest_period_files.outputs.result }}"
